# Generated by Django 6.0.5 on 2026-06-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Pickup', 'Cash on Pickup'), ('UPI on Pickup', 'UPI on Pickup')], default='Cash on Pickup', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Missed Pickup', 'Missed Pickup')], default='Pending', max_length=20),
        ),
    ]
